### ISSUE TITLE
Selecting a category named with uppercase creates a new one in lowercase

### ISSUE THREAD

**Issue by d3jv** [Kobu-Labs/nowaster-web#77]
When creating a new session and picking an already existing category, such as PB071, creates a new category called pb071 instead. Selecting categories that are all lowercase works as expected.

**Comment by Kobu** [comment]
@d3jv  can you please retest this on the latest code on branch `77-selecting-a-category-named-with-uppercase-creates-a-new-one-in-lowercase` ?

**Comment by d3jv** [comment]
Seems to be working fine.
